### ISSUE TITLE
Application crashes file searching

### ISSUE THREAD

**Issue by tomers** [TextAnalysisTool/TextAnalysisTool.github.io#2]
Hi,

Application crashed while I hit F2 or F3 several times.
Please see attached file for details.

![untitled](https://cloud.githubusercontent.com/assets/83443/9382196/1ef5d578-4747-11e5-9070-e814d4bbc620.png)

Thanks,
Tomer

**Comment by DavidAnson** [comment]
Please see TextAnalysisTool/Releases#14 for more information. Sorry for the trouble!
